version: '3.8'

services:
  front1:
    build: .
    ports:
      - "8081:8080"
    networks:
      - app-network

  front2:
    build: .
    ports:
      - "8082:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - front1
      - front2

networks:
  app-network: