version: '3.8'

services:
  front1:
    build: ./
    ports:
      - "3000:8080"
    networks:
      - front-network

  front2:
    build: ./
    ports:
      - "3001:8080"
    networks:
      - front-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front-network
    depends_on:
      - front1
      - front2

networks:
  front-network: